version: "3.8"

services:
  userdb:
    image: mysql:latest
    container_name: snms-user-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - snms-server

  postdb:
    image: mysql:latest
    container_name: snms-post-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${POST_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-post-data:/var/lib/mysql
    networks:
      - snms-server

  redis:
    image: redis:7.0-alpine
    container_name: snms-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - snms-server

volumes:
  mysql-user-data:
  mysql-post-data:
  redis-data:

networks:
  snms-server:
    driver: bridge
