server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  messages:
    encoding: UTF-8

  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 40MB

cloud:
  aws:
    s3:
      bucket: mysnmsbucket
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      stack:
        auto: false

jwt:
  secret: ${JWT_SIGN_KEY}
  issuer: snms